### ISSUE TITLE
Unable to run since last week

### ISSUE THREAD

**Issue by aibradford** [Samik081/beets-beatport4#12] opened 2023-08-17 15:24 UTC
I have everything working fine, until last week when all my devices running beats had the same issue at the same time.
Did the API change again?

I reset the password, but I'm still instructed to fix my config, which is all correct.

Can anyone tell me what is going on?

**Comment by Samik081** [comment] 2023-08-17 16:18
Hey @aibradford, I checked and everything works fine for me. Do you get any specific error? 
Could you please check the following:
1. Version of `beets-beatport4` package you are using by running the following command:
    ```
    pip show beets-beatport4
    ```
    The newest version is 0.3.2 If it's not the one you have, please try upgrading the version and trying again:
    ```
    pip install --upgrade beets-beatport4
    ```
2. Verbose log from the `beets import` process by adding `-vv` switch to the command like following:
    ```
    beet -vv import -t 'file.mp3'
    ```
    The log should contain the following entries from `beatport4` plugin:
    ```
    beatport4: Started authorizing to the API using username and password
    beatport4: Authorized with username and password as <USER> <<EMAIL>>
    beatport4: Authorization code: <AUTH_CODE>
    beatport4: Exchanged authorization code for the access token: {"access_token": "<ACCESS_TOKEN>", "expires_in": 36000, "token_type": "Bearer", "scope": "app:docs user:dj", "refresh_token": "<REFRESH_TOKEN>"}
    ```
    What logs from the `beatport4` plugin do you see? Please remember not to copy any credentials such as tokens.

**Comment by aibradford** [comment] 2023-08-18 12:21
For some reason, after I changed my password, it wasn't accepting it. I changed it again to a simpler password, and now it's working again. 
The password worked fine to log into Beatport but was not being accepted in my config. *shrugs*

**Comment by Samik081** [comment] 2023-08-24 18:33
I can't really reproduce it with more info or logs, I've tried the very long password with all the special characters, and it worked for me :/.

Since you managed to find the fix yourself and I can't reproduce it, I'm closing this issue. Feel free to write again if you spot anything else (and attach the logs, please! :)).

**Closed by Samik081** 2023-08-24 18:33 UTC
Labels: wontfix
